---
apiVersion: v1
kind: Service
metadata: 
  name: facebook-svc
  labels: 
    app: facebook
spec:
  type: LoadBalancer
  ports:
    - port: 80  
      targetPort: 8080
      protocol: TCP
  selector:
    app: fbapp